
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost


development:
  <<: *default
  database: BakedNoms_development
 
test:
  <<: *default
  database: BakedNoms_test

production:
  <<: *default
  database: BakedNoms_production
  
